---
include:
  - board: nice_nano
    shield: reviung41
  - board: nice60
  - board: nice60//zmk
    artifact-name: nice60_zmk_variant
  - board: nice_nano//zmk
    shield: reviung41
    artifact-name: reviung_zmk_var_test
